#ifndef __SOLACE_DEMOS_EXECUTION_TIME_MEASUREMENT_HPP__
#define __SOLACE_DEMOS_EXECUTION_TIME_MEASUREMENT_HPP__

#include <chrono>

void START_TIMER();
double END_TIMER();

#endif  //__SOLACE_DEMOS_EXECUTION_TIME_MEASUREMENT_HPP__
